@startuml
!include ..\lib_eventstorming.puml

Command("CreateArticle") [
    创建文章
    --触发事件--
    --属性--
    文章名
    文章描述
    文章内容
    文章作者
    --规则--
    文章名不能为空
    文章描述不能为空
    文章内容不能为空
    至少一位文章作者
]
Command("UpdateArticleInfo") [
    更新文章信息
    --触发事件--
    --属性--
    文章ID
    文章名
    文章描述
    --规则--
    文章名不能为空
    文章描述不能为空
]
Command("BanArticle") [
    封禁文章
    --触发事件--
    --属性--
    文章ID
    封禁时间
    封禁时长
    --规则--
   封禁时长必须大于0
]
Command("ReportArticle") [
    举报文章
    --触发事件--
    --属性--
    文章ID
    --规则--
]
Command("UpdateArticleFavoriteCount") [
    更新文章收藏数
    --触发事件--
    已收藏文章
    已取消收藏文章
    --属性--
    文章ID
    收藏数
    --规则--
    收藏数不为NULL
]
Command("UpdateArticleViewCount") [
    更新文章浏览量
    --触发事件--
    浏览记录已创建
    --属性--
    文章ID
    浏览量
    --规则--
    文章必须存在
    浏览量不为NULL
]
Command("UpdateArticleTags") [
    更新文章标签集
    --触发事件--
    --属性--
    文章ID
    标签集
    --规则--
]
Command("UpdateArticleCategories") [
    更新文章分类集
    --触发事件--
    --属性--
    文章ID
    分类
    --规则--
]
Command("UpdateArticleCommentCount") [
    更新文章评论数
    --触发者--
    已创建文章评论
    已删除文章评论
    --属性--
    文章ID
    评论数
    --规则--
    评论数不为NULL
]
Command("UpdateArticleCategoryInfo") [
    更新文章分类信息
    --触发者--
    已更新分类信息事件
    --属性--
    文章ID
    分类ID
    分类名
    --规则--
    分类必须存在
    分类名不为空
]
Command("UpdateArticleAuthorInfo")[
    更新文章作者信息
    --触发事件--
    已更新用户信息
    --属性--
    文章ID
    用户ID
    作者名
    --规则--
    用户必须存在
    用户名不为空
]
Command("UpdateArticleTagInfo") [
    更新文章标签信息
    --触发者--
    已更新标签信息
    --属性--
    文章ID
    标签ID
    标签名
    --规则--
    标签必须存在
    标签名不为空
]
Command("UpdateArticleVisibility") [
    更新文章可见性
    --触发事件--
    --属性--
    文章ID
    文章可见性
    --规则--
    文章可见性不为NULL
]
Command("UpdateArticleSticky") [
    更新文章置顶
    --触发事件--
    --属性--
    文章ID
    文章置顶标识
    --规则--
    文章置顶标识不为NULL
]
Command("UpdateArticleCommentFlag") [
    更新文章评论标识
    --触发事件--
    --属性--
    文章ID
    文章评论标识
    --规则--
    文章评论标识不为NULL
]
Command("UpdateArticlePrice") [
    更新文章价格
    --触发事件--
    --属性--
    文章ID
    价格
    --规则--
    价格必须大于等于0
]
Command("UpdateArticleLikeCount") [
    更新文章点赞数
    --触发事件--
    已点赞文章
    已取消点赞文章
    --属性--
    文章ID
    点赞数
    --规则--
    点赞数不为NULL
]
@enduml
