@startuml
!include ..\lib_eventstorming.puml

Aggregate("Article") [
    文章
    --属性--
    标题
    描述
    内容
    封面
    附件
    价格
    可见性
    置顶状态
    评论状态
    封禁时间
    封禁时长
]

Aggregate("ArticleAuthor") [
    文章作者
    --属性--
    文章ID
    作者ID
    作者名
]

Aggregate("ArticleCategory") [
    文章分类
    --属性--
    文章ID
    分类ID
    分类名
]

Aggregate("ArticleStatistics") [
    文章统计
    --属性--
    文章ID
    点赞数
    收藏数
    评论数
    浏览数
]

Aggregate("ArticleTag") [
    文章标签
    --属性--
    文章ID
    标签ID
    标签名
]

Article -right-> ArticleCategory
Article -right-> ArticleTag
Article -right-> ArticleStatistics
Article -right-> ArticleAuthor
@enduml
