@startuml
!include ..\lib_eventstorming.puml
DomainEvent("ArticleCategoriesUpdated") [
    文章分类集已更新
    --监听行为--
    更新分类引用数
]
DomainEvent("ArticleCreated") [
    文章已创建
    --监听行为--
    更新用户作品数
]
DomainEvent("ArticleLikeCountUpdated") [
    文章点赞数已更新
    点赞数
    --监听行为--
    更新用户点赞数
]
DomainEvent("ArticleTagsUpdated") [
    文章标签集已更新
    --监听行为--
    更新标签引用数
]
DomainEvent("ArticleViewCountUpdated") [
    文章浏览量已更新
    --监听形式--
    更新用户浏览量
]
@enduml
