@startuml
!include ..\lib_eventstorming.puml
DomainEvent("ArticleCreated") [
    已创建文章
    --属性--
    作者ID
    --监听者--
    该文章作者
]
DomainEvent("ArticleLikeCountUpdated") [
    已更新文章点赞数
    --属性--
    作者ID
    点赞数
    --监听者--
    该文章作者
]
DomainEvent("ArticleFavoriteCountUpdated") [
    已更新文章收藏数
    --属性--
    作者ID
    收藏数
    --监听者--
    该文章作者
]
DomainEvent("ArticleLiked") [
    已点赞文章
    --属性--
    作者ID
    --监听者--
    该文章
    操作者
]
DomainEvent("ArticleUnliked") [
    已取消点赞文章
    --属性--
    作者ID
    --监听者--
    该文章
    操作者
]
DomainEvent("ArticleCommentCreated") [
    已创建文章评论
    --属性--
    文章ID
    --监听者--
    该评论文章
]
DomainEvent("ArticleCommentDeleted") [
    已删除文章评论
    --属性--
    文章ID
    --监听者--
    该评论文章
]
DomainEvent("ArticleCommentLiked") [
    已点赞文章评论
    --属性--
    文章评论ID
    --监听者--
    该评论文章
    该评论作者
    操作者
]
DomainEvent("ArticleCommentUnliked") [
    已取消点赞文章评论
    --属性--
    文章评论ID
    --监听者--
    该评论文章
    该评论作者
    操作者
]
DomainEvent("ArticleCommentLikeCountUpdated") [
    已更新文章评论点赞数
    --属性--
    文章评论ID
    点赞数
    --监听者--
    该评论作者
]
DomainEvent("ArticleCategoriesUpdated") [
    已更新文章分类集
    --属性--
    文章ID
    分类ID
    --监听者--
    该文章
    该分类
]
DomainEvent("ArticleTagsUpdated") [
已更新文章标签集
    --属性--
    文章ID
    标签ID
    --监听者--
    该文章
    该标签
]
@enduml
