@startuml
ArticleCommentCreated       -down-> UpdateArticleCommentCount
ArticleCommentDeleted       -down-> UpdateArticleCommentCount
ArticleCommentReplyCreated  -down-> UpdateArticleCommentReplyCount
ArticleCommentReplyCreated  -down-> UpdateArticleCommentCount
ArticleCommentReplyDeleted  -down-> UpdateArticleCommentReplyCount
ArticleCommentReplyDeleted  -down-> UpdateArticleCommentCount
@enduml
