@startuml

CreateArticle                   -down-> Article
UpdateArticleInfo               -down-> Article
BanArticle                      -down-> Article
ReportArticle                   -down-> Article
UpdateArticleFavoriteCount      -down-> Article
UpdateArticleTags                -down-> Article
UpdateArticleCategories         -down-> Article
UpdateArticleCommentCount       -down-> Article
UpdateArticleCategoryInfo       -down-> Article
UpdateArticleAuthorInfo         -down-> Article
UpdateArticleTagInfo            -down-> Article
UpdateArticleVisibility         -down-> Article
UpdateArticleSticky             -down-> Article
UpdateArticleCommentFlag        -down-> Article
UpdateArticlePrice              -down-> Article
UpdateArticleLikeCount          -down-> Article
UpdateArticleViewCount          -down-> Article

Article -down-> ArticleCategoriesUpdated
Article -down-> ArticleCreated
Article -down-> ArticleLikeCountUpdated
Article -down-> ArticleTagsUpdated
Article -down-> ArticleViewCountUpdated
@enduml
