@startuml
ArticleCommentCreated       -down-> UpdateArticleCommentCount
ArticleCommentCreated       -down-> UpdateArticleCommentReplyCount
ArticleCommentDeleted       -down-> UpdateArticleCommentCount
ArticleCommentDeleted       -down-> UpdateArticleCommentReplyCount
@enduml
