@startuml

CreateArticle                   -down-> Article
UpdateArticleState              -down-> Article
UpdateArticleInfo               -down-> Article
BanArticle                      -down-> Article
ReportArticle                   -down-> Article
UpdateArticleFavoriteCount      -down-> Article
UpdateArticleTag                -down-> Article
UpdateArticleCategories         -down-> Article
CreateArticleComment            -down-> Article
ReportArticleComment            -down-> Article
DeleteArticleComment            -down-> Article
UpdateArticleCommentCount       -down-> Article
UpdateArticleCommentReplyCount  -down-> Article
UpdateArticleCommentSticky      -down-> Article
UpdateArticleCommentVisibility  -down-> Article
UpdateArticleCommentInfo        -down-> Article
UpdateArticleCategoryInfo       -down-> Article
UpdateArticleAuthorInfo         -down-> Article
UpdateArticleTagInfo            -down-> Article
UpdateArticleVisibility         -down-> Article
UpdateArticleSticky             -down-> Article
UpdateArticleCommentFlag        -down-> Article
UpdateArticlePrice              -down-> Article

Article-down->ArticleCreated
Article-down->ArticleFavoriteCountUpdated
Article-down->ArticleCommentCreated
Article-down->ArticleCommentDeleted
Article-down->ArticleCategoriesUpdated
Article-down->ArticleTagsUpdated
@enduml
