@startuml
!include ..\lib_eventstorming.puml

DomainEvent("StarLiked")[
    已点赞星球
    --属性--
    星球ID
    点赞数量
    --监听者--
    星球
    操作者
]
DomainEvent("StarUnliked")[
    已取消点赞星球
    --属性--
    星球ID
    取消点赞数量
    --监听者--
    星球
    操作者
]
@enduml
