@startuml
!include ..\lib_eventstorming.puml

Command("CreateTag") [
    创建标签
    --触发者--
    管理员
    --属性--
    标签名
    标签描述
    标签图标
    --规则--
    1. 标签名不能为空
    2. 标签描述不能为空
    3. 标签名必须唯一
]

Command("UpdateTagInfo") [
    更新标签信息
    --触发者--
    管理员
    --属性--
    标签ID
    标签名
    标签描述
    标签图标
    --规则--
    1. 标签名不能为空
    2. 标签必须存在
]
Command("UpdateTagRefCount") [
    更新标签引用次数
    --触发者--
    已更新文章标签集事件
    --属性--
    标签ID
    引用次数
    --规则--
    1. 标签必须存在
]
Command("DeleteTag") [
    删除标签
    --触发者--
    管理员
    --属性--
    标签ID
    --规则--
    1. 标签必须存在
    2. 标签未被使用
]
@enduml
