@startuml
!include ..\lib_eventstorming.puml

Command("CreateTag") [
    创建标签
    --触发事件--
    --属性--
    标签名
    标签描述
    标签图标
    --规则--
    标签名不能为空
    标签描述不能为空
    标签图标不能为空
    不存在同名标签
]
Command("UpdateTagInfo") [
    更新标签信息
    --触发事件--
    --属性--
    标签ID
    标签名
    标签描述
    标签图标
    --规则--
    标签必须存在
    标签名不能为空
    标签描述不能为空
    标签图标不能为空
]
Command("UpdateTagRefCount") [
    更新标签引用次数
    --触发事件--
    已更新文章标签集
    --属性--
    标签ID
    引用次数
    --规则--
    标签必须存在
    引用次数不为NULL
]
Command("DeleteTag") [
    删除标签
    --触发事件--
    --属性--
    标签ID
    --规则--
    标签必须存在
    标签未被使用
]
@enduml
