@startuml
'https://plantuml.com/sequence-diagram
!include ..\lib_eventstorming.puml

!if VIEW_COMMENT
Comment("need")[
    1. 创建标签
    2. 删除标签
    3. 更新标签信息
]
!endif

!include command.puml
!include domain.puml
!include event.puml
!include relationCDE.puml

!if VIEW_QUERY
!include query.puml
!endif

'!include ..\relationEC.puml
@enduml
