@startuml
!include ..\lib_eventstorming.puml
DomainEvent("ArticleCommentReplyCreated") [
    已创建文章评论回复
    --监听行为--
    更新文章评论回复数
    更新文章评论数
]
DomainEvent("ArticleCommentReplyDeleted") [
    已删除文章评论回复
    --监听行为--
    更新文章评论回复数
    更新文章评论数
]
DomainEvent("ArticleCommentReplyLikeCountUpdated") [
    已更新文章评论回复点赞数
    --监听者--
    更新用户点赞数
]
@enduml
