@startuml
!include ..\lib_eventstorming.puml

Command("CreateCategory") [
    创建分类
    --触发事件--
    --属性--
    分类名
    --规则--
    分类名不能为空
    不存在同名分类
]
Command("UpdateCategoryInfo") [
    更新分类信息
    --触发行为--
    --属性--
    分类ID
    分类名
    --规则--
    分类必须存在
    分类名不能为空
    不存在同名分类
]
Command("UpdateCategoryRefCount") [
    更新分类引用数
    --触发事件--
    更新文章分类集
    --属性--
    分类ID
    文章数
    --规则--
    分类必须存在
    文章数不为空
]
Command("DeleteCategory") [
    删除分类
    --触发行为--
    --属性--
    分类ID
    --规则--
    分类必须存在
    分类未被使用
]
@enduml
