@startuml
!include ..\lib_eventstorming.puml

Aggregate("AdminUser") [
    管理员
    --属性--
    管理员ID
    名称
    手机号
    密码
    刷新令牌
    创建时间
    权限集
    角色集
]

Aggregate("AdminUserRole") [
    管理员角色
    --属性--
    管理员ID
    角色ID
    角色名称
]

Aggregate("AdminUserPermission") [
    管理员权限
    --属性--
    管理员ID
    权限码
    权限备注
    源角色ID集(不进行持久化)
]

AdminUser -right-> AdminUserRole
AdminUser -right-> AdminUserPermission

@enduml
