@startuml
!include ..\lib_eventstorming.puml

Command("RegisterMemberWithPassword") [
    通过密码方式注册用户
    --触发器--
    游客
    --属性--
    用户名
    密码
    --规则--
    1. 用户名不能为空
    2. 用户名必须唯一
    3. 密码不能为空
]
Command("RegisterMemberWithPhone") [
    通过手机号方式注册用户
    --触发器--
    游客
    --属性--
    手机号
    --规则--
    1. 手机号未绑定帐号
]
Command("UpdateMemberPhone") [
    更新用户手机号
    --触发器--
    当前用户
    --属性--
    用户ID
    手机号
    --规则--
    1. 手机号未绑定帐号
]
Command("UpdateMemberPassword") [
    更新用户密码
    --触发器--
    当前用户
    --属性--
    用户ID
    新密码
    --规则--
    1. 密码不能为空
]
Command("UpdateMemberInfo") [
    更新用户信息
    --触发器--
    当前用户
    --属性--
    用户ID
    用户名
    个性签名
    --规则--
    1. 用户名不能为空
    2. 用户名必须唯一
]
Command("UpdateMemberRank") [
    更新用户等级分
    --触发器--
    已计算用户即将获得的等级分事件
    --属性--
    用户ID
    等级分
    --规则--
    1. 用户必须存在
    2. 用户拥有等级
]
Command("DeleteMember") [
    删除用户
    --触发器--
    当前用户
    --属性--
    用户ID
    --规则--
    1. 用户必须存在
    2. 星球会员全部到期
]
Command("ReportMember") [
    举报用户
    --触发者--
    用户
    --属性--
    用户ID
    --规则--
    1. 用户必须存在
    2. 用户未被封禁
]
Command("UpMemberLevel") [
     等级提升
     --触发者--
     已更新用户等级分事件
     --属性--
     用户ID
     --规则--
    1. 当前等级为将提升等级的下级
    3. 如过1->2积分须大于等于233
    4. 如果2->3积分须大于等于3306
    5. 如果3->4积分须大于等于8848
    6. 如果4->5积分须大于等于50000
    8. 如果5->6积分须大于等于66666
]
Command("UpdateMemberLikeCount") [
    更新用户点赞数
    --触发者--
    已更新文章点赞数事件
    已更新星球点赞数事件
    已更新文章评论点赞数事件
    已更新星球评论点赞数事件
    --属性--
    用户ID
    点赞数
    --规则--
    1. 用户必须存在
]
Command("UpdateMemberFanCount") [
    更新用户粉丝数
    --触发者--
    已关注用户事件
    已取消关注用户事件
    --属性--
    用户ID
    粉丝数
    --规则--
    1. 用户必须存在
]
Command("UpdateMemberWorkCount") [
    更新用户作品数
    --触发者--
    已创建文章事件
    --属性--
    用户ID
    作品数
    --规则--
    1. 用户必须存在
]

Command("BanMember") [
    封禁用户
    --触发者--
    管理员
    (TODO)
    --属性--
    用户ID
    封禁时间
    封禁时长
    --规则--
    1. 用户必须存在
    2. 用户未被封禁
    3. 封禁时长必须大于0
]
Command("UnbanMember") [
    取消封禁用户
    --触发者--
    管理员
    (TODO)
    --属性--
    用户ID
    --规则--
    1. 用户必须存在
    2. 用户已被封禁
]
Command("FollowMember") [
    关注用户
    --触发者--
    当前用户
    --属性--
    用户ID
    被关注ID
    --规则--
    1. 用户必须存在
    2. 用户未被关注
]
Command("UnfollowMember") [
    取消关注用户
    --触发者--
    当前用户
    --属性--
    用户ID
    被关注ID
    --规则--
    1. 用户必须存在
    2. 用户已被关注
]

Command("CreateFavorites") [
    创建收藏夹
    --触发者--
    已通过密码方式注册用户事件
    已通过手机号方式注册用户事件
    当前用户
    --属性--
    收藏夹名
    收藏夹描述
    --规则--
    1. 收藏夹名不能为空
    2. 收藏夹描述不能为空
    3. 相同用户不能有同名收藏夹
    4. 只能拥有一个默认收藏夹
]
Command("UpdateFavoritesInfo") [
    更新收藏夹信息
    --触发者--
    当前用户
    --属性--
    收藏夹ID
    收藏夹名
    收藏夹描述
    --规则--
    1. 收藏夹必须存在
    2. 收藏夹名不能为空
    3. 相同用户不能有同名收藏夹
    4. 收藏夹描述不能为空
    5. 默认收藏夹不能修改
]
Command("AddArticleToFavorite") [
    收藏文章
    --触发者--
    当前用户
    --属性--
    用户ID
    收藏夹ID
    文章ID
    --规则--
    1. 文章必须存在
    2. 未在当前收藏夹中
]
Command("RemoveArticleFromFavorite") [
    取消收藏文章
    --触发者--
    当前用户
    --属性--
    用户ID
    收藏夹ID
    文章ID
    --规则--
    1. 文章必须存在
    2. 已在当前收藏夹中
]
Command("DeleteFavorites") [
    删除收藏夹
    --触发者--
    当前用户
    --属性--
    用户ID
    收藏夹ID
    --规则--
    1. 收藏夹必须存在
    2. 非默认收藏夹
    3. 该用户为收藏夹拥有者
]

Command("UpdateMemberFollowingCount") [
    更新用户关注数
    --触发者--
    已关注用户事件
    已取消关注用户事件
    --属性--
    用户ID
    关注数
    --规则--
    1. 用户必须存在
]

Command("UpdateFavoritesArticleCount") [
    更新用户收藏文章数
    --触发者--
    已收藏文章事件
    已取消收藏文章事件
    --属性--
    用户ID
    收藏文章数
    --规则--
    1. 用户必须存在
]

Command("UpdateMemberStarInfo") [
    更新用户星球信息
    --触发者--
    创建星球事件
    已更新星球信息事件
    删除星球事件
    --属性--
    用户ID
    会员星球ID
    会员星球名
    --规则--
    1. 用户必须存在
    2. 会员星球必须存在
    3. 会员星球名不能为空
]

Command("UpdateMemberStardustCount")[
    更新用户星尘
    --触发者--
    已加入星球事件
    已离开星球事件
    --属性--
    用户ID
    星尘
    --规则--
    1. 用户必须存在
]

Command("UpdateBlackMemberInfo") [
    更新拉黑用户信息
    --触发者--
    已更新用户信息事件
    --属性--
    用户ID
    被拉黑用户ID
    被拉黑用户名
    --规则--
    1. 用户必须存在
    2. 被拉黑用户必须存在
]

Command("UpdateFollowMemberInfo") [
    更新关注用户信息
    --触发者--
    已更新用户信息事件
    --属性--
    用户ID
    关注用户ID
    关注用户名
    --规则--
    1. 用户必须存在
    2. 关注用户必须存在
]
@enduml
