@startuml
!include ..\lib_eventstorming.puml

Aggregate("Member") [
    用户
    --属性--
    用户ID
    帐号
    密码
    手机号
    昵称
    个性签名
    等级
    余额
    是否被封禁
    封禁时间
]

Aggregate("MemberStatistics") [
    用户统计
    --属性--
    用户ID
    等级分
    点赞数
    粉丝数
    举报数
    关注数
    作品数
    播放量
]

Aggregate("BlockMember") [
    拉黑用户
    --属性--
    用户ID
    拉黑用户ID
    拉黑用户名
]

Aggregate("FollowMember") [
    关注用户
    --属性--
    用户ID
    关注用户ID
    关注会员名
]

Aggregate("Favorites") [
    收藏夹
    --属性--
    用户ID
    名称
    描述
    是否默认
]

Aggregate("ArticleFavoriteStatistics") [
    收藏夹收藏统计
    --属性--
    收藏夹ID
    文章数
]

Aggregate("FavoritesArticle") [
    会员收藏记录
    --属性--
    收藏夹ID
    文章ID
    收藏时间
]

Member -right-> MemberPermission
Member -right-> MemberStatistics
Member -right-> BlockMember
Member -right-> FollowMember
Member -right-> Favorites
Favorites -right-> ArticleFavoriteStatistics
Favorites -right-> FavoritesArticle

@enduml
