@startuml
!include ..\lib_eventstorming.puml
DomainEvent("MemberInfoUpdated") [
    已更新用户信息
    --监听行为--
    更新拉黑用户信息
    更新关注用户信息
    更新文章作者信息
    更新文章评论信息
    更新文章评论回复信息
]
DomainEvent("MemberFollowed") [
    已关注用户
    --监听行为--
    更新用户关注数
    更新用户粉丝数
]
DomainEvent("MemberUnfollowed") [
    已取消关注用户
    更新用户关注数
    更新用户粉丝数
]

Event("ArticleAddedToFavorites") [
    已收藏文章
    --监听行为--
    更新文章收藏数
]
Event("ArticleRemovedFromFavorites") [
    已取消收藏文章
    --监听行为--
    更新文章收藏数
]
@enduml
