@startuml
MemberFollowed              -down-> UpdateMemberFollowingCount
MemberUnfollowed            -down-> UpdateMemberFollowingCount
ArticleAddedToFavorites     -down-> UpdateFavoritesArticleCount
ArticleRemovedFromFavorites -down-> UpdateFavoritesArticleCount
@enduml
