@startuml
MemberInfoUpdated           -down-> UpdateBlackMemberInfo
MemberInfoUpdated           -down-> UpdateFollowMemberInfo
MemberFollowed              -down-> UpdateMemberFollowingCount
MemberFollowed              -down-> UpdateMemberFanCount
MemberUnfollowed            -down-> UpdateMemberFollowingCount
MemberUnfollowed            -down-> UpdateMemberFanCount
FavoritedArticle            -down-> UpdateMemberFavoritesArticles
UnFavoritedArticle          -down-> UpdateMemberFavoritesArticles
MemberRankUpdated           -down-> LevelUp
@enduml
