@startuml
MemberInfoUpdated               -down-> UpdateBlackMemberInfo
MemberInfoUpdated               -down-> UpdateFollowMemberInfo
RanksCalculated                 -down-> UpdateMemberRank
MemberFollowed                  -down-> UpdateMemberFollowingCount
MemberFollowed                  -down-> UpdateMemberFanCount
MemberUnfollowed                -down-> UpdateMemberFollowingCount
MemberUnfollowed                -down-> UpdateMemberFanCount
ArticleAddedToFavorites         -down-> UpdateMemberFavoritesArticleCount
ArticleRemovedFromFavorites     -down-> UpdateMemberFavoritesArticleCount
MemberCheckedIn                 -down-> CalculateRank
ArticleAddedToFavorites         -down-> CalculateRank
ArticleRemovedFromFavorites     -down-> CalculateRank
MemberLikeCountUpdated          -down-> CalculateRank
MemberRankUpdated               -down-> MemberLevelUp
@enduml
