@startuml
RegisterMemberWithPassword            -down-> Member
RegisterMemberWithPhone               -down-> Member
UpdateMemberPhone                   -down-> Member
UpdateMemberPassword                -down-> Member
UpdateMemberInfo                    -down-> Member
CheckIn                              -down-> Member
UpdateMemberRank                    -down-> Member
DeleteMember                        -down-> Member
ReportMember                        -down-> Member
LevelUp                          -down-> Member
UpdateMemberLikeCount                   -down-> Member
UpdateMemberFanCount                    -down-> Member
UpdateMemberFollowingCount              -down-> Member
UpdateMemberWorkCount                   -down-> Member
BanMember                           -down-> Member
UnbanMember                         -down-> Member
FollowMember                        -down-> Member
UnfollowMember                      -down-> Member
CreateFavorites                     -down-> Member
UpdateFavoritesInfo                 -down-> Member
FavoriteArticle                     -down-> Member
UnFavoriteArticle                   -down-> Member
DeleteFavorites                     -down-> Member
CalculateWillReceiveRanks           -down-> Member
UpdateMemberFavoritesArticles       -down-> Member
UpdateMemberStarInfo                -down-> Member
UpdateMemberStardustCount                -down-> Member
UpdateBlackMemberInfo               -down-> Member
UpdateFollowMemberInfo              -down-> Member



Member-down->MemberInfoUpdated
Member-down->MemberRankUpdated
Member-down->MemberFollowed
Member-down->MemberUnfollowed
Member-down->FavoritedArticle
Member-down->UnFavoritedArticle
Member-down->MemberRegisteredWithPassword
Member-down->MemberRegisteredWithPhone
@enduml
