@startuml
UpdatedMemberInfo           -down-> UpdateBlackMemberInfo
UpdatedMemberInfo           -down-> UpdateFollowMemberInfo
CalculatedWillReceiveRanks  -down-> UpdateMemberRank
FollowedMember              -down-> UpdateMemberFollowings
FollowedMember              -down-> UpdateMemberFans
UnFollowedMember            -down-> UpdateMemberFollowings
UnFollowedMember            -down-> UpdateMemberFans
FavoritedArticle            -down-> UpdateMemberFavoritesArticles
UnFavoritedArticle          -down-> UpdateMemberFavoritesArticles
SignedIn                    -down-> CalculateWillReceiveRanks
FavoritedArticle            -down-> CalculateWillReceiveRanks
UnFavoritedArticle          -down-> CalculateWillReceiveRanks
UpdatedMemberLikes          -down-> CalculateWillReceiveRanks
UpdatedMemberRank           -down-> LevelRaise
@enduml
