@startuml
'https://plantuml.com/sequence-diagram
!include ..\lib_eventstorming.puml
!if VIEW_COMMENT
Comment("need")[

]
!endif

!include command.puml
!include domain.puml
!include event.puml
!include relationCDE.puml

!if VIEW_QUERY
!include query.puml
!endif

!include relationEC.puml
@enduml
