@startuml
!include ..\lib_eventstorming.puml

Command("CreateCoupon") [
    创建优惠券
    --触发者--
    作者
    --属性--
    星球ID
    --规则--
    1.优惠价格不能大于原价
    2.优惠价格不能为零
    3.优惠券二维码不能重复
    4.一个星球只能同时存在一个有效的优惠券
]
Command("DisableCoupon") [
    停用优惠券
    --触发者--
    作者
    --属性--
    优惠券ID
    --规则--
]
Command("DeleteCoupon") [
    删除优惠券
    --触发者--
    作者或计时器
    --属性--
    优惠券ID
    --规则--
    1.优惠券必须停用后才能删除
    2.优惠券必须存在
]
Command("updateCoupon") [
    更新优惠券
    --触发者--
    作者
    --属性--
    优惠券ID
    优惠券价格
    --规则--
    1.优惠券在停用状态才能被修改
]
Command("UseCoupon") [
    使用优惠券
    --触发者--
    用户
    --属性--
    优惠券ID
    用户ID
    星球ID
    --规则--
    1.优惠券的使用次数没有超过规定的次数
    2.使用时间没有超过优惠券有效期
]
@enduml
