@startuml
!include ..\lib_eventstorming.puml

Command("CreateStar") [
    创建星球
    --触发者--
    当前用户
    --属性--
    星球ID
    星球名
    星球描述
    星球价格
    --规则--
    1. 星球名不能为空
    2. 星球描述不能为空
    3. 星球名必须唯一
    4. 星球价格必须大于0
]
Command("DeleteStar") [
    删除星球
    --触发者--
    当前用户
    --属性--
    星球ID
    --规则--
    1. 星球必须存在
    2. 星球会员全部到期
]

Command("JoinStar") [
    加入星球
    --触发者--
    当前用户
    --属性--
    用户ID
    用户名
    星球ID
    加入时间
    --规则--
    1. 星球必须存在
    2. 用户未加入星球
]
Command("UpdateStardustCountInfo") [
    更新星尘信息
    --触发器--
    已更新用户信息事件
    --属性--
    星尘ID
    星尘名
    --规则--
    1. 星尘必须存在
]

Command("UpdateStardustCount") [
    更新星尘
    --触发者--
    已加入星球事件
    已离开星球事件
    --属性--
    星球ID
    --规则--
    1. 星球必须存在
    2. 星尘必须存在
]

Command("LeaveStar") [
    离开星球
    --触发者--
    当前用户
    --属性--
    星尘ID
    星球ID
    --规则--
    1. 星球必须存在
    2. 用户已加入星球
]

Command("LikeStar") [
    点赞星球
    --触发者--
    当前用户
    --属性--
    用户ID
    星球ID
    --规则--
    1. 星球必须存在
    2. 未点赞
]
Command("UnLikeStar") [
    取消点赞星球
    --触发者--
    当前用户
    --属性--
    用户ID
    星球ID
    --规则--
    1. 星球必须存在
    2. 已点赞
]
Command("CreateStarComment") [
    创建星球评论
    --触发者--
    当前用户
    --属性--
    星球ID
    用户ID
    评论内容
    --规则--
    1. 星球必须存在
    2. 当前用户已加入星球
    3. 评论内容不能为空
]

Command("DeleteStarComment") [
    删除星球评论
    --触发者--
    当前用户
    --属性--
    星球ID
    星球评论ID
    --规则--
    1. 星球评论必须存在
    2. 当前用户为星主或管理员
    3. 该评论属于该星球
]
Command("LikeStarComment") [
    点赞星球评论
    --触发者--
    当前用户
    --属性--
    星球ID
    星球评论ID
    --规则--
    1. 星球评论必须存在
    2. 未点赞
]
Command("UnlikeStarComment") [
    取消点赞星球评论
    --触发者--
    当前用户
    --属性--
    星球ID
    星球评论ID
    --规则--
    1. 星球评论必须存在
    2. 已点赞
]

Command("UpdateStarCommentAuthorInfo") [
    更新星球评论作者信息
    --触发者--
    已更新用户信息事件
    --属性--
    星球评论ID
    星球评论作者
    星球评论作者名
    --规则--
    1. 星球评论必须存在
    2. 星球评论作者必须存在
]

Command("UpdateStarLikeCount") [
    更新星球点赞数
    --触发者--
    已点赞星球事件
    已取消点赞星球事件
    --属性--
    星球ID
    点赞数
    --规则--
    1. 星球必须存在
]

Command("UpdateStarCommentCount") [
    更新星球评论数
    --触发者--
    已创建星球评论事件
    已删除星球评论事件
    --属性--
    星球ID
    评论数
    --规则--
    1. 星球必须存在
]

Command("UpdateStarCommentLikeCount") [
    更新星球评论点赞数
    --触发者--
    已点赞星球评论事件
    已取消点赞星球评论事件
    --属性--
    星球评论ID
    点赞数
    --规则--
    1. 星球评论必须存在
]
@enduml
