@startuml
!include ..\lib_eventstorming.puml

Command("CreateStarComment") [
    创建星球评论
    --触发事件--
    --属性--
    星球ID
    用户ID
    用户名
    内容
    --规则--
    星球必须存在
    用户必须存在
    用户名不能为空
    内容不能为空
]
Command("DeleteStarComment") [
    删除星球评论
    --触发事件--
    --属性--
    星球评论ID
    --规则--
    星球评论必须存在
]
Command("UpdateStarCommentLikeCount") [
    更新星球评论点赞数
    --触发事件--
    星球评论点赞记录已创建
    星球评论点赞记录已删除
    --属性--
    星球评论ID
    点赞数
    --规则--
    星球评论必须存在
    点赞数不为NULL
]
Command("UpdateStarCommentReportCount") [
    更新星球评论举报数
    --触发事件--
    星球评论举报记录已创建
    星球评论举报记录已删除
    --属性--
    星球评论ID
    举报数
    --规则--
    星球评论必须存在
    举报数不为NULL
]
Command("UpdateStarCommentReplyCount") [
    更新星球评论回复数
    --触发事件--
    星球评论回复已创建
    星球评论回复已删除
    --属性--
    星球评论ID
    回复数
    --规则--
    星球评论必须存在
    回复数不为NULL
]
Command("PinStarComment") [
    置顶星球评论
    --属性--
    星球评论ID
    --规则--
    星球评论必须存在
    置顶状态为未置顶
]
Command("UnPinStarComment") [
    取消置顶星球评论
    --属性--
    星球评论ID
    --规则--
    星球评论必须存在
    置顶状态为置顶
]
Command("UpdateStarCommentInfo") [
    更新星球评论信息
    --触发事件--
    已更新用户信息
    --属性--
    星球评论ID
    用户ID
    用户名
    --规则--
    用户必须存在
    用户名不能为空
]
@enduml
