@startuml
!include ..\lib_eventstorming.puml

DomainEvent("StarCommentCreated") [
    星球评论已创建
    --监听行为--
    更新星球评论数
]
DomainEvent("StarCommentDeleted") [
    星球评论已删除
    --监听行为--
    更新星球评论数
]
DomainEvent("StarCommentLikeCountUpdated") [
    星球评论点赞数已更新
    --监听行为--
    更新星球点赞数
]
DomainEvent("StarCommentReplyCountUpdated") [
    星球评论回复数已更新
    --监听行为--
    更新星球评论数
]

Event("StarCommentPinned") [
    星球评论已置顶
    --监听行为--
]
Event("StarCommentUnPinned") [
    星球评论已取消置顶
    --监听行为--
]
Event("StarCommentReportCountUpdated") [
    星球评论举报数已更新
    --监听行为--
]
Event("StarCommentInfoUpdated") [
    星球评论信息已更新
    --监听行为--
]
@enduml
