@startuml
JoinedStar                  -down-> UpdateStardustCount
LeftStar                    -down-> UpdateStardustCount
StarCreatedComment          -down-> UpdateStarCommentCount
StarDeletedComment          -down-> UpdateStarCommentCount
@enduml
