@startuml
CreateStarComment            -down-> StarComment
DeleteStarComment            -down-> StarComment
UpdateStarCommentLikeCount   -down-> StarComment
UpdateStarCommentReportCount -down-> StarComment
UpdateStarCommentReplyCount  -down-> StarComment
PinStarComment               -down-> StarComment
UnPinStarComment             -down-> StarComment
UpdateStarCommentInfo        -down-> StarComment

StarComment -down-> StarCommentCreated
StarComment -down-> StarCommentDeleted
StarComment -down-> StarCommentLikeCountUpdated
StarComment -down-> StarCommentReportCountUpdated
StarComment -down-> StarCommentReplyCountUpdated
StarComment -down-> StarCommentPinned
StarComment -down-> StarCommentUnPinned
StarComment -down-> StarCommentInfoUpdated
@enduml
