@startuml
'https://plantuml.com/sequence-diagram
!include ..\lib_eventstorming.puml
!if VIEW_COMMENT
Comment("need")[
发布星球评论
删除星球评论
统计星球点赞数
统计星球回复数
统计星球举报数
更新星球评论信息
置顶星球评论
]
!endif

!include command.puml
!include domain.puml
!include event.puml
!include relationCDE.puml

!if VIEW_QUERY
!include query.puml
!endif

!include relationEC.puml
@enduml
