@startuml
!define VIEW_COMMENT
!define VIEW_QUERY

!include admin_user/view.puml
!include article/view.puml
!include article_comment/view.puml
!include article_comment_like/view.puml
!include article_comment_reply/view.puml
!include article_like/view.puml
!include category/view.puml
!include check_in/View.puml
!include member/view.puml
!include role/view.puml
!include tag/view.puml
!include view_history/view.puml

!include relationEC.puml
@enduml
