@startuml
'Article
ArticleCreated                  -down-> UpdateMemberWorkCount
ArticleLikeCountUpdated         -down-> UpdateMemberLikeCount
ArticleCategoriesUpdated        -down-> UpdateCategoryRefCount
ArticleTagsUpdated              -down-> UpdateTagRefCount
ArticleLiked                    -down-> CalculateRank
ArticleUnliked                  -down-> CalculateRank
ArticleCommentLiked             -down-> CalculateRank
ArticleCommentUnliked           -down-> CalculateRank
ArticleCommentLikeCountUpdated  -down-> UpdateMemberLikeCount


'category
UpdatedCategoryInfo -down-> UpdateArticleCategoryInfo

'member
UpdatedMemberInfo           -down-> UpdateStardustInfo
UpdatedMemberInfo           -down-> UpdateArticleCommentAuthorInfo
UpdatedMemberInfo           -down-> UpdateStarCommentAuthorInfo
UpdatedMemberInfo           -down-> UpdateArticleAuthorInfo
RegisteredMemberByPassword  -down-> CreateFavorites
RegisteredMemberByPhone     -down-> CreateFavorites
FavoritedArticle            -down-> UpdateArticleFavorites
UnFavoritedArticle          -down-> UpdateArticleFavorites

'role
UpdatedRolePermissions  -down-> UpdateAdminUserRolePermissions
UpdatedRoleInfo         -down-> UpdateAdminUserRoleInfo

'star
CreatedStar                 -down-> UpdateMemberStarInfo
DeletedStar                 -down-> UpdateMemberStarInfo
JoinedStar                  -down-> UpdateMemberStardustCount
LeftStar                    -down-> UpdateMemberStardustCount
LikedStar                   -down-> CalculateRank
UnLikedStar                 -down-> CalculateRank
LikedStarComment            -down-> CalculateRank
UnLikedStarComment          -down-> CalculateRank
UpdatedStarLikes            -down-> UpdateMemberLikeCount
UpdatedStarCommentLikes     -down-> UpdateMemberLikeCount
UpdatedStarInfo             -down-> UpdateMemberStarInfo

'tag
UpdatedTagInfo -down-> UpdateArticleTagInfo
@enduml
