@startuml
'Article
ArticleCreated                  -down-> UpdateMemberWorkCount
ArticleLikeCountUpdated         -down-> UpdateMemberLikeCount
ArticleCategoriesUpdated        -down-> UpdateCategoryRefCount
ArticleTagsUpdated              -down-> UpdateTagRefCount
ArticleViewCountUpdated         -down-> UpdateMemberViewCount
ArticleFavoriteCountUpdated     -down-> UpdateFavoritesArticleCount

'ArticleComment
ArticleCommentCreated           -down-> UpdateArticleCommentCount
ArticleCommentDeleted           -down-> UpdateArticleCommentCount
ArticleCommentLikeCountUpdated  -down-> UpdateMemberLikeCount

'ArticleCommentLike
ArticleCommentLiked         -down-> UpdateArticleCommentLikeCount
ArticleCommentUnliked       -down-> UpdateArticleCommentLikeCount

'ArticleCommentReply
ArticleCommentReplyCreated          -down-> UpdateArticleCommentReplyCount
ArticleCommentReplyCreated          -down-> UpdateArticleCommentCount
ArticleCommentReplyDeleted          -down-> UpdateArticleCommentReplyCount
ArticleCommentReplyDeleted          -down-> UpdateArticleCommentCount
ArticleCommentReplyLikeCountUpdated -down-> UpdateMemberLikeCount

'ArticleLike
ArticleLiked                -down-> UpdateArticleLikeCount
ArticleUnliked              -down-> UpdateArticleLikeCount

'Category
CategoryInfoUpdated -down-> UpdateArticleCategoryInfo

'CheckIn
CheckedIn -down-> UpdateMemberRank

'Member
MemberInfoUpdated               -down-> UpdateArticleAuthorInfo
MemberInfoUpdated               -down-> UpdateArticleCommentInfo
MemberInfoUpdated               -down-> UpdateArticleCommentReplyInfo
MemberInfoUpdated               -down-> UpdateBlackMemberInfo
MemberInfoUpdated               -down-> UpdateFollowMemberInfo
MemberFollowed                  -down-> UpdateMemberFanCount
MemberUnfollowed                -down-> UpdateMemberFanCount

'Tag
TagInfoUpdated -down-> UpdateArticleTagInfo

'ViewHistory
ViewHistoryCreated       -down-> UpdateArticleViewCount

'role
UpdatedRolePermissions  -down-> UpdateAdminUserRolePermissions
UpdatedRoleInfo         -down-> UpdateAdminUserRoleInfo
@enduml
