@startuml
'Article
ArticleCreated                  -down-> UpdateMemberWorkCount
ArticleLikeCountUpdated         -down-> UpdateMemberLikeCount
ArticleCategoriesUpdated        -down-> UpdateCategoryRefCount
ArticleTagsUpdated              -down-> UpdateTagRefCount
ArticleViewCountUpdated         -down-> UpdateMemberViewCount

'ArticleComment
ArticleCommentCreated           -down-> UpdateArticleCommentCount
ArticleCommentDeleted           -down-> UpdateArticleCommentCount
ArticleCommentReplyCountUpdated -down-> UpdateArticleCommentCount
ArticleCommentLikeCountUpdated  -down-> UpdateMemberLikeCount

'ArticleCommentLike
ArticleCommentLiked         -down-> UpdateArticleCommentLikeCount
ArticleCommentUnliked       -down-> UpdateArticleCommentLikeCount

'ArticleCommentReply
ArticleCommentReplyCreated          -down-> UpdateArticleCommentReplyCount
ArticleCommentReplyDeleted          -down-> UpdateArticleCommentReplyCount
ArticleCommentReplyLikeCountUpdated -down-> UpdateMemberLikeCount

'ArticleLike
ArticleLiked                -down-> UpdateArticleLikeCount
ArticleUnliked              -down-> UpdateArticleLikeCount

'Category
CategoryInfoUpdated -down-> UpdateArticleCategoryInfo

'CheckIn
CheckedIn -down-> UpdateMemberRank

'Member
MemberInfoUpdated               -down-> UpdateArticleAuthorInfo
MemberInfoUpdated               -down-> UpdateArticleCommentInfo
MemberInfoUpdated               -down-> UpdateArticleCommentReplyInfo
MemberInfoUpdated               -down-> UpdateBlackMemberInfo
MemberInfoUpdated               -down-> UpdateFollowMemberInfo
MemberFollowed                  -down-> UpdateMemberFanCount
MemberUnfollowed                -down-> UpdateMemberFanCount

'Tag
TagInfoUpdated -down-> UpdateArticleTagInfo

'ViewHistory
ViewHistoryCreated       -down-> UpdateArticleViewCount

'role
RolePermissionsUpdated  -down-> UpdateAdminUserRolePermissions
RoleInfoUpdated         -down-> UpdateAdminUserRoleInfo

'StarComment
StarCommentCreated -down-> UpdateStarCommentCount
StarCommentDeleted -down-> UpdateStarCommentCount
StarCommentLikeCountUpdated -down-> UpdateStarLikeCount
StarCommentReplyCountUpdated -down-> UpdateStarCommentCount

'UnField
StarCommentLikeCreated -down-> UpdateStarCommentLikeCount
StarCommentLikeDeleted -down-> UpdateStarCommentLikeCount
StarCommentReportCreated -down-> UpdateStarCommentReportCount
StarCommentReportDeleted -down-> UpdateStarCommentReportCount
@enduml
