@startuml
'Article
CreatedArticle              -down-> UpdateMemberWorks
UpdatedArticleLikes         -down-> UpdateMemberLikes
LikedArticle                -down-> CalculateWillReceiveRanks
UnlikedArticle              -down-> CalculateWillReceiveRanks
LikedArticleComment         -down-> CalculateWillReceiveRanks
UnlikedArticleComment       -down-> CalculateWillReceiveRanks
UpdatedArticleCommentLikes  -down-> UpdateMemberLikes

'category
UpdatedCategoryInfo -down-> UpdateArticleCategoryInfo

'member
UpdatedMemberInfo           -down-> UpdateStardustInfo
UpdatedMemberInfo           -down-> UpdateArticleCommentAuthorInfo
UpdatedMemberInfo           -down-> UpdateStarCommentAuthorInfo
UpdatedMemberInfo           -down-> UpdateArticleAuthorInfo
RegisteredMemberByPassword  -down-> CreateFavorites
RegisteredMemberByPhone     -down-> CreateFavorites
FavoritedArticle            -down-> UpdateArticleFavorites
UnFavoritedArticle          -down-> UpdateArticleFavorites

'role
UpdatedRolePermissions  -down-> UpdateAdminUserRolePermissions
UpdatedRoleInfo         -down-> UpdateAdminUserRoleInfo

'star
CreatedStar                 -down-> UpdateMemberStarInfo
DeletedStar                 -down-> UpdateMemberStarInfo
JoinedStar                  -down-> UpdateMemberStardust
LeftStar                    -down-> UpdateMemberStardust
LikedStar                   -down-> CalculateWillReceiveRanks
UnLikedStar                 -down-> CalculateWillReceiveRanks
LikedStarComment            -down-> CalculateWillReceiveRanks
UnLikedStarComment          -down-> CalculateWillReceiveRanks
UpdatedStarLikes            -down-> UpdateMemberLikes
UpdatedStarCommentLikes     -down-> UpdateMemberLikes
UpdatedStarInfo             -down-> UpdateMemberStarInfo

'tag
UpdatedTagInfo -down-> UpdateArticleTagInfo
@enduml
