# 将该文件移动到自己虚拟机里
# 并在此文件同级目录下
#  创建 ./mysql/data 记得开放 文件权限
#  创建 ./redis/data 记得开放 文件权限
#  创建 ./redis/conf 记得开放 文件权限
services:
  db:
    image: mysql:8.0.33
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

  redis:
    image: redis:6.2.12
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - ./redis/conf:/redis/config:rw
      # 数据文件
      - ./redis/data/:/redis/data/:rw
    command: "redis-server /redis/config/redis.conf"
    privileged: true
