@startuml
!include ..\lib_eventstorming.puml

Command("CreateOrder") [
    创建订单
    --触发者--
    (TODO)
    --属性--
    订单ID
    订单金额
    实付金额
    --规则--
    1. 订单金额必须大于零
    3. 实付金额必须大于等于0
]
Command("RefundOrder") [
    退款订单
    --触发者--
    当前用户
    --属性--
    订单ID
    --规则--
    1. 订单必须存在
    2. 订单状态不为退款成功
]
Command("PayOrder") [
    支付订单
    --触发者--
    当前用户
    --属性--
    订单ID
    --规则--
    1. 订单必须存在
    2. 订单状态为已待支付
]
Command("CancelOrder") [
    取消订单
    --触发者--
    当前用户
    --属性--
    订单ID
    --规则--
    1. 订单必须存在
    2. 订单状态为已待支付
]
@enduml
