@startuml
!include ..\lib_eventstorming.puml

DomainEvent("UpdatedRolePermissions") [
    已更新角色权限集
    --监听行为--
    更新角色权限信息
]
DomainEvent("UpdatedRoleInfo") [
    已更新角色信息
    --监听行为--
    更新角色信息
]
@enduml
