@startuml
CreateRole              -down-> Role
UpdateRoleInfo          -down-> Role
UpdateRolePermissions   -down-> Role
DeleteRole              -down-> Role

Role -down-> RoleInfoUpdated
Role -down-> RolePermissionsUpdated
@enduml
