@startuml
!include ..\lib_eventstorming.puml

Aggregate("Star") [
    星球
    --属性--
    星球ID
    星球名
    星球描述
    星球价格
    --行为--
'    更新星球信息
'    更新星球价格
'    更新星球评论数
'    更新星球点赞数
'    更新星球星尘数
]

Aggregate("StarStatistics") [
    星球统计
    --属性--
    星球ID
    星球点赞数
    星球评论数
    星尘数
    --行为--
'    更新点赞数
'    更新评论数
'    更新星尘数
]

Star -right-> StarStatistics
@enduml
