@startuml
!include ..\lib_eventstorming.puml

DomainEvent("StarCreated") [
    已创建星球
    --监听行为--
'    更新用户星球集
]
DomainEvent("StarDeleted") [
    已删除星球
    --监听行为--
'    更新用户星球集
]

Event("StarCommentCountUpdated") [
    已更新星球评论数
    --监听行为--
'    更新星球评论数
]
Event("StarLikeCountStatistized") [
    已统计星球点赞数
    --监听行为--
'    更新用户点赞数
]
Event("StarDustCountUpdated") [
    已更新星尘数
    --监听行为--
'    更新星球评论数
]
@enduml
