@startuml
JoinedStar                  -down-> UpdateStardust
LeftStar                    -down-> UpdateStardust
LikedStar                   -down-> UpdateStarLikes
UnLikedStar                 -down-> UpdateStarLikes
CreatedStarComment          -down-> UpdateStarComments
DeletedStarComment          -down-> UpdateStarComments
LikedStarComment            -down-> UpdateStarCommentLikes
UnLikedStarComment          -down-> UpdateStarCommentLikes
@enduml
