@startuml
CreateStar                      -down-> Star
DeleteStar                      -down-> Star
UpdateStarLikeCount             -down-> Star
UpdateStarCommentCount          -down-> Star

Star -down-> StarCreated
Star -down-> StarDeleted
Star -down-> StarCommentCountUpdated
Star -down-> StarLikeCountStatistized
@enduml
