@startuml
'https://plantuml.com/sequence-diagram
!include ..\lib_eventstorming.puml
!if VIEW_COMMENT
Comment("need")[
1.创建星球
2.删除星球
3.更新星球评论数
4.统计星球点赞数
5.点赞星球
6.取消点赞星球
]
!endif

!include command.puml
!include domain.puml
!include event.puml
!include relationCDE.puml

!if VIEW_QUERY
!include query.puml
!endif

!include relationEC.puml
@enduml
