@startuml
!include ..\lib_eventstorming.puml

DomainEvent("ArticleLiked") [
    已点赞文章
    --属性--
    作者ID
    --监听者--
    该文章
    操作者
]
DomainEvent("ArticleUnliked") [
    已取消点赞文章
    --属性--
    作者ID
    --监听者--
    该文章
    操作者
]
@enduml
