@startuml
!include ..\lib_eventstorming.puml

Command("LikeArticleComment") [
    点赞文章评论
    --触发事件--
    --属性--
    用户ID
    文章评论ID
    --规则--
    用户必须存在
    文章评论必须存在
]
Command("UnlikeArticleComment") [
    取消点赞文章评论
    --触发事件--
    --属性--
    用户ID
    文章评论ID
    --规则--
    用户必须存在
    文章评论必须存在
]
@enduml
