@startuml

LikeArticleComment      -down-> ArticleCommentLike
UnlikeArticleComment    -down-> ArticleCommentLike

ArticleCommentLike -down-> ArticleCommentLiked
ArticleCommentLike -down-> ArticleCommentUnliked

@enduml
