# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven Test on Pull Request to Master

# 触发条件：当有 PR 合并到 master 分支时运行
on:
  pull_request:
    branches:
      - master

jobs:
  run-maven-tests:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Java 环境
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8' # 你可以根据需要选择版本，例如 8, 11, 17 等
          distribution: 'temurin'

      # 运行 Maven 测试命令
      - name: Run Maven Tests
        run: mvn test

